### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by hubtheflow** [chung-leong/av#5]
Hello, I've written a class which watermarks video, everything works well except the fact that a segmentation fault occurs in av_stream_write_pcm when processing certain videos. av_stream_write_pcm processes only several samples in such videos and then the program crashes with segmentation fault.

It looks like a memory corruption, my code is OOP and I tried to reproduce the error on a plain php code without success. 

I will post my class if you will be unable to track the issue from this brief description.

**Comment by chung-leong** [comment]
I need more information. What's the operation system? If you can, find out what version of ffmpeg you have. The API does differ considerably between versions. I'll need the PHP code as well as the video that triggers the crash.

**Comment by hubtheflow** [comment]
It crashes both on windows and linux, My windows setup is PHP 5.3.27 and recent zeranoe builds. I've tried many of them:
ffmpeg-20130809-git-3b2e99f-win32-shared.7z
ffmpeg-20130807-git-b45b1d7-win32-shared.7z
ffmpeg-20130801-git-f118b41-win32-shared.7z 
ffmpeg-20130731-git-69fe25c-win32-shared.7z 
ffmpeg-20130726-git-f3f4e13-win32-shared.7z 
ffmpeg-20130723-git-55db06a-win32-shared.7z 
ffmpeg-20130726-git-f3f4e13-win32-shared.7z 
ffmpeg-20130723-git-55db06a-win32-shared.7z
ffmpeg-20130720-git-835eee8-win32-shared.7z
ffmpeg-20130716-git-38b701a-win32-shared.7z
ffmpeg-20130706-git-63d7684-win32-shared.7z
ffmpeg-20130630-git-ff130d7-win32-shared.7z
ffmpeg-20130623-git-c329713-win32-shared.7z
ffmpeg-20130619-git-9ead060-win32-shared.7z
ffmpeg-20130614-git-6fe419b-win32-shared.7z
ffmpeg-20130613-git-443b29e-win32-shared.7z
Some of them give segfault, and some show the "error encountered writing file header". You can try ffmpeg-20130613-git-443b29e-win32-shared.7z - it will give the segmentation fault.
My linux setup is latest Debian with ffmpeg from deb-multimedia repository, all setup is done according to your manual.
Will give you the php class and video a bit later.

**Comment by hubtheflow** [comment]
https://github.com/hubtheflow/wmvideo - the class
the video and image causing segfault http://s000.tinyupload.com/?file_id=63571749442425767291 ,
run it with following command:
php wmvideoconsole.php --source=directory --dest=directory --watermark=file
note:paths should be absolute

**Comment by chung-leong** [comment]
Thanks. I'll take a look at it. I'm going to be on the road next week. I might not be able to resolve this until I return.

**Comment by chung-leong** [comment]
Okay, looks like the issue might simple be a stupid typo. An incorrect name in a #ifdef means code meant for old versions of ffmpeg was being used instead of code for the newest version. The fix is checked into github. Will try to get the binary packages rebuilt.

**Comment by chung-leong** [comment]
Okay, try the new win32 binary and see if the problem persists: https://php-qb.googlecode.com/files/av-1.3-php-5.3-win32-32bit-ts-vc9.zip

**Comment by hubtheflow** [comment]
I've tested the new revision on windows and linux and the issue doesn't occur anymore. Thank you.

**Comment by hubtheflow** [comment]
found that the segmentation fault still occurs in av_stream_write_pcm with slightly another conditions, try running my class with the same test files specifying the frame #100 to save:
php wmvideoconsole.php --source=directory --dest=directory --watermark=file --frames=100

**Comment by chung-leong** [comment]
I'll take a look as soon as I return from my trip.

**Comment by chung-leong** [comment]
Agh, I was too hasty in fixing the code and ended up breaking the Linux build script. It should work now.

**Comment by hubtheflow** [comment]
I've rebuilt av from the master branch on debian linux, and tested like I [described here](https://github.com/chung-leong/av/issues/5#issuecomment-22652590), segmentation fault still occurs.

**Comment by chung-leong** [comment]
I forgot you're on Debian. That distro comes with libav instead of ffmpeg so the issue is somewhat different. It's wheezy you're using? I think the fall-back code is actually employed in this case.

Sent from my Windows Phone

**Comment by hubtheflow** [comment]
yes, I'm on debian wheezy, yes it's libav in there, btw it now comes from unofficial repository http://deb-multimedia.org

**Comment by chung-leong** [comment]
Thanks for the info. That's very helpful. The part where the crash occurs concerns audio resampling. It differs to a large degree between libav and ffmpeg and the different versions of the libraries. I'll try to nail the problem down.

Sent from my Windows Phone

**Comment by chung-leong** [comment]
Having some trouble reproducing the error. It didn't pop up in 32-bit version of wheezy. I'm downloading the 64-bit now. 

Can you run the following on the command line and tell me what it return?

grep "define LIBAVCODEC_VERSION_M" /usr/local/include/libavcodec/version.h

I'm assuming the extension is being compiled against the library in /usr/local. If not, grep the file in /usr/include.

**Comment by hubtheflow** [comment]
here's the grep output:
#define LIBAVCODEC_VERSION_MAJOR 54
#define LIBAVCODEC_VERSION_MINOR 59
#define LIBAVCODEC_VERSION_MICRO 100

Please rebuild the extension for windows (av-1.3-php-5.3-win32-32bit-ts-vc9) from the master, and I'll check if the issue still occurs on my windows setup.

**Comment by chung-leong** [comment]
I couldn't reproduce the segfault. Try `sudo apt-get install libswresample-dev` then rebuild the extension. libav has its own resampling library: libavresample, but there is no package for it. Only the library from ffmpeg proper is available.  

The current Windows binary should work at it is.

**Comment by hubtheflow** [comment]
installing libswresample-dev solves the issue on debian! Segmentation fault doesn't occur anymore when processing my test video.
I've also checked the latest windows binary- it doesn't occur there too.

I will test with more videos and close this issue later this week, if the segmentation fault won't reoccur.
